### ISSUE TITLE
why the performance is different from the paper ?

### ISSUE THREAD

**Issue by yehyaali151989w** [JohnnyPeng18/HiTyper#4]
Hello, 
Thank you for your work 
I have a question:
why the performance is different from the paper ?, for example in paper table Table 5: Comparison with static type inference tools

when using the static part only:  
 the performance for return value HiTyper 0.86, but in GitHub  Return Values 0.69

**Comment by JohnnyPeng18** [comment]
Thanks for your interest!

This is because the two "ExactMarch" scores are different. 

If you read the part discussing Table 5 in the paper, you will know the "ExactMatch" score in Table 5 represent the precision, and that's why there is another column named "number of correct annotations" to approximate recall. 0.86 means that 86% of HiTyper results match the GT. We did not use the "Exact Match" as a recall in the paper because static analysis tools can easily fail to infer types.

However,  the "ExactMatch" score used in README represents the recall to make it comparable with DL techniques, though it is not fair. 0.69 means that HiTyper can correctly infer 69% of return values in the dataset. That's why the score of arguments is very low, and the score of return values is different from the paper.

**Comment by yehyaali151989w** [comment]
why in READM you mention that
 "Old results:

If you want the exact experiment results stated in the paper, please download them at this [link]."
Do you mean the results are different from the paper you mean when we use the whole tool(DL+static part)
 why two results old and new?

**Comment by JohnnyPeng18** [comment]
This is because:
1) This repo is actively maintained, and the code is frequently changed.  
2) The benchmark dataset is also evolving. The benchmark dataset used in the paper is updated now.
Therefore, we do not provide any guarantee that the tool now can yield the same results as in the paper. 
We do not recommend you directly copy the results in the paper without actually implementing the tool. If you want to compare with HiTyper, just run it on your own dataset to acquire the latest results. However, we still provide the original results in case you want to directly use them.

**Comment by yehyaali151989w** [comment]
I was just asking out of curiosity, thanks for answer
